---
- hosts: all
  gather_facts: true
  tasks:
    - name: Install DRBD
      include_role:
        name: drbd

- hosts: all[0]
  gather_facts: true
  tasks:
    - name: Syncronize DRBD
      command: drbdadm primary --force r0


- hosts: all
  gather_facts: true
  tasks:
    - name: Install PostgreSQL
      include_role:
        name: postgres

